version: '3.7'

services:
  travelmates_back:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  travelmates-db:
    image: postgres:12
    volumes:
      - travelmates_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5433:5432

volumes:
  travelmates_postgres_data:
