# Generated by Django 5.1.3 on 2024-11-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_prifile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='No bio provided'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='prifile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
